// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://knakbpgcazrxslavigbd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtuYWticGdjYXpyeHNsYXZpZ2JkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2ODI1OTMsImV4cCI6MjA2ODI1ODU5M30.IN-1nuol8X5fN7gF7E_NgiHDx80kwd0zg3aa-KPJVsA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});